constructor – wavy
constructor Function
73 statements
Source File
private pure elemental function constructor(fmin, fmax, df, ndirs, depth, grav, air_density, water_density, surface_tension) result(spectrum)
Constructor function for the spectrum object.
monochromatic
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: fmin
Minimum frequency bin [Hz]
real(kind=rk), intent(in) :: fmax
Maximum frequency bin [Hz]
real(kind=rk), intent(in) :: df
Frequency increment, df = f(n+1)/f(n)
integer, intent(in) :: ndirs
Number of directional bins
real(kind=rk), intent(in) :: depth
Mean water depth [m]
real(kind=rk), intent(in), optional :: grav
Gravitational acceleration [m/s^2]
real(kind=rk), intent(in), optional :: air_density
Air density [kg/m^3]
real(kind=rk), intent(in), optional :: water_density
Water density [kg/m^3]
real(kind=rk), intent(in), optional :: surface_tension
Surface tension [N/m]
Return Value type(spectrum_type)
Calls
Called By
Source Code
constructor
Source Code
pure elemental type(spectrum_type) function constructor(fmin,fmax,df,ndirs,&
  depth,grav,air_density,water_density,surface_tension) result(spectrum)
  !! Constructor function for the spectrum object.
  real(kind=rk),intent(in) :: fmin
    !! Minimum frequency bin [Hz]
  real(kind=rk),intent(in) :: fmax
    !! Maximum frequency bin [Hz]
  real(kind=rk),intent(in) :: df
    !! Frequency increment, df = f(n+1)/f(n)
  integer,intent(in) :: ndirs
    !! Number of directional bins
  real(kind=rk),intent(in) :: depth
    !! Mean water depth [m]
  real(kind=rk),intent(in),optional :: grav
    !! Gravitational acceleration [m/s^2]
  real(kind=rk),intent(in),optional :: air_density
    !! Air density [kg/m^3]
  real(kind=rk),intent(in),optional :: water_density
    !! Water density [kg/m^3]
  real(kind=rk),intent(in),optional :: surface_tension
    !! Surface tension [N/m]
  integer :: n
  integer :: nfreqs
  if(present(grav))then
    spectrum % grav = grav
  else
    spectrum % grav = 9.8_rk
  endif
  if(present(air_density))then
    spectrum % air_density = air_density
  else
    spectrum % air_density = 1.2_rk
  endif
  if(present(water_density))then
    spectrum % water_density = water_density
  else
    spectrum % water_density = 1e3_rk
  endif
  if(present(surface_tension))then
    spectrum % surface_tension = surface_tension
  else
    spectrum % surface_tension = 0.07_rk
  endif
  spectrum % depth = depth
  if(fmin == fmax)then
    !! monochromatic
    nfreqs = 1
  else
    nfreqs = int((log(fmax)-log(fmin))/log(df))
  endif
  allocate(spectrum % spec(nfreqs,ndirs))
  spectrum % spec = 0
  allocate(spectrum % f(nfreqs))
  allocate(spectrum % df(nfreqs))
  allocate(spectrum % k(nfreqs))
  allocate(spectrum % dk(nfreqs))
  allocate(spectrum % cp(nfreqs))
  allocate(spectrum % cg(nfreqs))
  allocate(spectrum % th(ndirs))
  if(nfreqs == 1)then
    spectrum % f(n) = fmin
  else
    do concurrent(n = 1:nfreqs)
      spectrum % f(n) = exp(log(fmin)+(n-1)*log(df))
    enddo
  endif
  do concurrent(n = 1:nfreqs)
    spectrum % k(n) = wavenumber(spectrum % f(n),         &
                                 spectrum % depth,        &
                                 spectrum % water_density,&
                                 spectrum % grav,         &
                                 spectrum % surface_tension)
  enddo
  spectrum % cp = twopi * spectrum % f / spectrum % k
  spectrum % cg = twopi * diff(spectrum % f) / diff(spectrum % k)
  do concurrent(n = 1:ndirs)
    spectrum % th(n) = (n-0.5*(ndirs+1))*twopi/ndirs
  enddo
  spectrum % df = diff(spectrum % f)
  spectrum % dk = diff(spectrum % k)
  if(ndirs > 1)then
    spectrum % dth = diff_periodic(spectrum % th)
    spectrum % dth(1) = spectrum % dth(2)
    spectrum % dth(ndirs) = spectrum % dth(ndirs-1)
  else
    spectrum % dth = [1]
  endif
  call spectrum % setCurrent2d([0._rk],[0._rk],[0._rk])
endfunction constructor
All Procedures
advect1dRank1 advect1dRank2 advect2dRank2 advectCentered2ndOrder advectCentered2ndOrder1dRank0 advectCentered2ndOrder1dRank1 advectCentered2ndOrder1dRank2 advectCentered2ndOrder2dRank0 advectCentered2ndOrder2dRank1 advectCentered2ndOrder2dRank2 advectUpwind1stOrder advectUpwind1stOrder1dRank0 advectUpwind1stOrder1dRank1 advectUpwind1stOrder1dRank2 advectUpwind1stOrder2dRank0 advectUpwind1stOrder2dRank1 advectUpwind1stOrder2dRank2 assign_array_1d assign_array_2d assign_spectrum_array_1d assign_spectrum_array_2d backward_euler backward_euler_domain backward_euler_spectrum constructor constructor constructor_1d constructor_2d diff diff_1d diff_2d diff_periodic diff_periodic_1d diff_periodic_2d domain_add_domain domain_add_real domain_div_domain domain_div_real domain_mult_domain domain_mult_real domain_sub_domain domain_sub_real domain_type domain_unary_minus donelanHamiltonHui donelanHamiltonHuiDirectionalSpectrum donelanHamiltonHuiDirectionalSpreading elevation eq eq exact_exponential exact_exponential_domain exact_exponential_spectrum forward_euler forward_euler_domain forward_euler_spectrum frequencyMoment frequencyMoment ge getAirDensity getAirDensity getAmplitude getAxisX getAxisY getCurrent_u getCurrent_u getCurrent_v getCurrent_v getDepth getDepth getDepthLevels getDirections getDirections getDirections2d getElevation getElevation getFrequency getFrequency getFrequency2d getGravity getGravity getGrid getGridRotation getGridSpacingX getGridSpacingXWithHalo getGridSpacingY getGridSpacingYWithHalo getGroupSpeed getGroupSpeed getGroupSpeed2d getLatitude getLongitude getLowerBounds getLowerBounds getPhaseSpeed getPhaseSpeed getPhaseSpeed2d getSpectrum getSpectrum getSpectrumArray getSurfaceTension getSurfaceTension getUpperBounds getUpperBounds getWaterDensity getWaterDensity getWaveAction getWavelength getWavenumber getWavenumber2d getWavenumberSpacing gravityClairaut grid_type gt horizontalAcceleration horizontalVelocity integrate integrate_domain integrate_spectrum isAllocated isAllocated isMonochromatic isOmnidirectional jonswap jonswapPeakFrequency le lt meanPeriod meanPeriod meanPeriodZeroCrossing meanPeriodZeroCrossing meanSquareSlope meanSquareSlopeDirectional momentum_x momentum_y momentumFlux_xx momentumFlux_xy momentumFlux_yy neq neq nondimensionalDepth nondimensionalEnergy nondimensionalFetch nondimensionalFrequency nondimensionalRoughness_H1986 nondimensionalRoughness_S1974 nondimensionalTime omnidirectionalSpectrum ones ones_int ones_real peakedness peakFrequency peakFrequencyDiscrete phillips piersonMoskowitz piersonMoskowitzPeakFrequency pressure range range_int range_real readJSON real2d_mult_spectrum real_add_domain real_add_spectrum real_div_domain real_div_spectrum real_mult_domain real_mult_spectrum real_sub_domain real_sub_spectrum saturationSpectrum sbf_DCCM2012 sbf_JONSWAP sds_DCCM2012 sdt_DCCM2012 setAirDensity setAirDensity setCurrent1d setCurrent2d setDepth setDepth setElevation setElevation setGravity setGravity setSpectrum1d setSpectrum1d setSpectrum2d setSpectrum2d setSpectrumArray1d1d setSpectrumArray1d2d setSpectrumArray2d2d setSurfaceTension setSurfaceTension setWaterDensity setWaterDensity significantSurfaceOrbitalVelocity significantWaveHeight significantWaveHeight sin_DCCM2012 snl_DCCM2012 spectrum_add_real spectrum_add_spectrum spectrum_div_real spectrum_div_spectrum spectrum_mult_real spectrum_mult_real2d spectrum_mult_spectrum spectrum_sub_real spectrum_sub_spectrum spectrum_type spectrum_unary_minus stokesDrift stokesDrift2d tile tile_1d_int tile_1d_real tile_2d_int tile_2d_real tile_3d_int tile_3d_real ursellNumber verticalAcceleration verticalVelocity waveAge wavenumber wavenumberMoment wavenumberMoment wavenumberSpectrum writeJSON writeJSON zeros zeros_int zeros_real
Call graph
constructor calls f, wavenumber, cg, diff_periodic, th, cp, setcurrent2d, dk, k, dth, spec, diff
diff_periodic calls diff_periodic_1d, diff_periodic_2d
diff calls diff_1d, diff_2d
spectrum_type calls constructor