sin_DCCM2012 – wavy
sin_DCCM2012 Function
60 statements
Source File
public pure elemental function sin_DCCM2012(spectrum, wspd, wdir, input_height, ustar, vonkarman) result(tendency)
Uses:
mod_spectrum
mod_aerodynamic_drag
mod_const
TODO implement currents averaged over the effective depth layer for modulation of phase speed.
Returns a spectrum instance with the wave growth ($S_{in}$) tendency formulated by Donelan et al. (2012) and based on the sheltering hypothesis by Jeffreys (1924, 1925).
The result instance has the units of 1/s. This source function must be re-evaluated if any of the input parameters change.
References:
Donelan, M. A., M. Curcic, S. S. Chen, and A. K. Magnusson, 2012: Modeling waves and wind stress, J. Geophys. Res. Oceans, 117, C00J23, doi:10.1029/2011JC007787.
Jeffreys, H., 1924: On the formation of waves by wind, Proc. R. Soc. A, 107, 189–206.
Jeffreys, H., 1925: On the formation of waves by wind, II, Proc. R. Soc. A, 110, 341–347.
Arguments
Type Intent Optional Attributes Name
type(spectrum_type), intent(in) :: spectrum
Input spectrum instance
real(kind=rk), intent(in) :: wspd
Input wind speed [m/s]
real(kind=rk), intent(in) :: wdir
Input wind direction [rad], mathematical convention
real(kind=rk), intent(in) :: input_height
Height of input wind speed [m/s]
real(kind=rk), intent(in) :: ustar
Air-side friction velocity [m/s]
real(kind=rk), intent(in) :: vonkarman
Von Karman constant
Return Value type(spectrum_type)
Calls
Source Code
sin_DCCM2012
Source Code
pure elemental function sin_DCCM2012(spectrum,wspd,wdir,input_height,ustar,&
  vonkarman) result(tendency)
  !! TODO implement currents averaged over the effective depth layer for
  !! modulation of phase speed.
  !! Returns a spectrum instance with the wave growth ($S_{in}$) tendency
  !! formulated by Donelan et al. (2012) and based on the sheltering hypothesis
  !! by Jeffreys (1924, 1925).
  !!
  !! The result instance has the units of 1/s. This source function must be
  !! re-evaluated if any of the input parameters change.
  !!
  !! References:
  !!
  !! Donelan, M. A., M. Curcic, S. S. Chen, and A. K. Magnusson, 2012: Modeling
  !! waves and wind stress, *J. Geophys. Res. Oceans*, **117**, C00J23,
  !! doi:10.1029/2011JC007787.
  !!
  !! Jeffreys, H., 1924: On the formation of waves by wind, *Proc. R. Soc. A*,
  !! **107**, 189–206.
  !!
  !! Jeffreys, H., 1925: On the formation of waves by wind, II, *Proc. R. Soc.
  !! A*, **110**, 341–347.
  use mod_spectrum,only:spectrum_type
  use mod_aerodynamic_drag,only:windAtReferenceHeight
  use mod_const,only:twopi
  type(spectrum_type),intent(in) :: spectrum
    !! Input spectrum instance
  real(kind=rk),intent(in) :: wspd
    !! Input wind speed [m/s]
  real(kind=rk),intent(in) :: wdir
    !! Input wind direction [rad], mathematical convention
  real(kind=rk),intent(in) :: input_height
    !! Height of input wind speed [m/s]
  real(kind=rk),intent(in) :: ustar
    !! Air-side friction velocity [m/s]
  real(kind=rk),intent(in) :: vonkarman
    !! Von Karman constant
  type(spectrum_type) :: tendency
  real(kind=rk),dimension(:,:),allocatable :: s_in
  real(kind=rk),dimension(:),allocatable :: f
  real(kind=rk),dimension(:),allocatable :: th
  real(kind=rk),dimension(:),allocatable :: k
  real(kind=rk),dimension(:),allocatable :: cp
  real(kind=rk),dimension(:),allocatable :: omega
  real(kind=rk),dimension(:),allocatable :: half_wavelength
  real(kind=rk),dimension(:),allocatable :: wspd_input
  real(kind=rk) :: grav
  real(kind=rk) :: rho_air
  real(kind=rk) :: rho_water
  real(kind=rk),parameter :: a1_windsea = 0.11_rk
  real(kind=rk),parameter :: a1_swell = 0.01_rk
  real(kind=rk),parameter :: a1_opposed = 0.10_rk
  real(kind=rk),parameter :: field_scale_negative = a1_opposed / a1_windsea
  real(kind=rk),parameter :: field_scale_swell = a1_swell / a1_opposed
  real(kind=rk),dimension(:,:),allocatable :: sheltering_coefficient
  integer :: nfreq,nfreqs
  integer :: ndir,ndirs
  tendency = spectrum
  grav = spectrum % getGravity()
  rho_air = spectrum % getAirDensity()
  rho_water = spectrum % getWaterDensity()
  f = spectrum % getFrequency()
  th = spectrum % getDirections()
  k = spectrum % getWavenumber()
  cp = spectrum % getPhaseSpeed()
  half_wavelength = 0.5_rk*spectrum % getWavelength()
  omega = twopi*f
  nfreqs = size(f)
  ndirs = size(th)
  ! Evaluate wind speed at height of half-wavelength of each wave component
  wspd_input = windAtReferenceHeight(wspd,input_height,half_wavelength,ustar,&
    vonkarman)
  allocate(s_in(nfreqs,ndirs))
  allocate(sheltering_coefficient(nfreqs,ndirs))
  ! Set the initial sheltering coefficient to a1_windsea everywhere
  sheltering_coefficient = a1_windsea
  do concurrent(nfreq = 1:nfreqs,ndir = 1:ndirs)
    ! If input is negative, adjust the sheltering coefficient to a1_opposed
    if(wspd_input(nfreq)*cos(wdir-th(ndir))-cp(nfreq) < 0)then
      sheltering_coefficient(nfreq,ndir) = sheltering_coefficient(nfreq,ndir)&
        * field_scale_negative
      ! If input is negative but has positive misalignment, adjust the
      ! sheltering coefficient to a1_swell
      if(cos(wdir-th(ndir)) > 0)then
        sheltering_coefficient(nfreq,ndir) = sheltering_coefficient(nfreq,ndir)&
        * field_scale_swell
      endif
    endif
  enddo
  do concurrent(ndir=1:ndirs)
    s_in(:,ndir) = sheltering_coefficient(:,ndir)*rho_air/rho_water            &
      *(wspd_input*cos(wdir-th(ndir))-cp)*abs(wspd_input*cos(wdir-th(ndir))-cp)&
      *omega*k/grav
  enddo
  tendency = s_in
  deallocate(s_in,sheltering_coefficient)
endfunction sin_DCCM2012
All Procedures
advect1dRank1 advect1dRank2 advect2dRank2 advectCentered2ndOrder advectCentered2ndOrder1dRank0 advectCentered2ndOrder1dRank1 advectCentered2ndOrder1dRank2 advectCentered2ndOrder2dRank0 advectCentered2ndOrder2dRank1 advectCentered2ndOrder2dRank2 advectUpwind1stOrder advectUpwind1stOrder1dRank0 advectUpwind1stOrder1dRank1 advectUpwind1stOrder1dRank2 advectUpwind1stOrder2dRank0 advectUpwind1stOrder2dRank1 advectUpwind1stOrder2dRank2 assign_array_1d assign_array_2d assign_spectrum_array_1d assign_spectrum_array_2d backward_euler backward_euler_domain backward_euler_spectrum constructor constructor constructor_1d constructor_2d diff diff_1d diff_2d diff_periodic diff_periodic_1d diff_periodic_2d domain_add_domain domain_add_real domain_div_domain domain_div_real domain_mult_domain domain_mult_real domain_sub_domain domain_sub_real domain_type domain_unary_minus donelanHamiltonHui donelanHamiltonHuiDirectionalSpectrum donelanHamiltonHuiDirectionalSpreading elevation eq eq exact_exponential exact_exponential_domain exact_exponential_spectrum forward_euler forward_euler_domain forward_euler_spectrum frequencyMoment frequencyMoment ge getAirDensity getAirDensity getAmplitude getAxisX getAxisY getCurrent_u getCurrent_u getCurrent_v getCurrent_v getDepth getDepth getDepthLevels getDirections getDirections getDirections2d getElevation getElevation getFrequency getFrequency getFrequency2d getGravity getGravity getGrid getGridRotation getGridSpacingX getGridSpacingXWithHalo getGridSpacingY getGridSpacingYWithHalo getGroupSpeed getGroupSpeed getGroupSpeed2d getLatitude getLongitude getLowerBounds getLowerBounds getPhaseSpeed getPhaseSpeed getPhaseSpeed2d getSpectrum getSpectrum getSpectrumArray getSurfaceTension getSurfaceTension getUpperBounds getUpperBounds getWaterDensity getWaterDensity getWaveAction getWavelength getWavenumber getWavenumber2d getWavenumberSpacing gravityClairaut grid_type gt horizontalAcceleration horizontalVelocity integrate integrate_domain integrate_spectrum isAllocated isAllocated isMonochromatic isOmnidirectional jonswap jonswapPeakFrequency le lt meanPeriod meanPeriod meanPeriodZeroCrossing meanPeriodZeroCrossing meanSquareSlope meanSquareSlopeDirectional momentum_x momentum_y momentumFlux_xx momentumFlux_xy momentumFlux_yy neq neq nondimensionalDepth nondimensionalEnergy nondimensionalFetch nondimensionalFrequency nondimensionalRoughness_H1986 nondimensionalRoughness_S1974 nondimensionalTime omnidirectionalSpectrum ones ones_int ones_real peakedness peakFrequency peakFrequencyDiscrete phillips piersonMoskowitz piersonMoskowitzPeakFrequency pressure range range_int range_real readJSON real2d_mult_spectrum real_add_domain real_add_spectrum real_div_domain real_div_spectrum real_mult_domain real_mult_spectrum real_sub_domain real_sub_spectrum saturationSpectrum sbf_DCCM2012 sbf_JONSWAP sds_DCCM2012 sdt_DCCM2012 setAirDensity setAirDensity setCurrent1d setCurrent2d setDepth setDepth setElevation setElevation setGravity setGravity setSpectrum1d setSpectrum1d setSpectrum2d setSpectrum2d setSpectrumArray1d1d setSpectrumArray1d2d setSpectrumArray2d2d setSurfaceTension setSurfaceTension setWaterDensity setWaterDensity significantSurfaceOrbitalVelocity significantWaveHeight significantWaveHeight sin_DCCM2012 snl_DCCM2012 spectrum_add_real spectrum_add_spectrum spectrum_div_real spectrum_div_spectrum spectrum_mult_real spectrum_mult_real2d spectrum_mult_spectrum spectrum_sub_real spectrum_sub_spectrum spectrum_type spectrum_unary_minus stokesDrift stokesDrift2d tile tile_1d_int tile_1d_real tile_2d_int tile_2d_real tile_3d_int tile_3d_real ursellNumber verticalAcceleration verticalVelocity waveAge wavenumber wavenumberMoment wavenumberMoment wavenumberSpectrum writeJSON writeJSON zeros zeros_int zeros_real
Call graph
sin_dccm2012 calls getfrequency, getwaterdensity, windatreferenceheight, getphasespeed, getwavenumber, getgravity, getwavelength, getairdensity, getdirections