tile – wavy
tile Interface
8 statements
Source File
public interface tile
Calls
Module Procedures
tile_1d_int tile_1d_real tile_2d_int tile_2d_real tile_3d_int tile_3d_real
Module Procedures
private pure function tile_1d_int(array, n) result(tiled_array)
Tiles the input array n times. Returns a tiled array that has rank equal to size(shape(array))+1 and that has values equal to values of array, repeated n times. This version is for 1-d input array of integers. This procedure is overloaded by the generic procedure tile.
Arguments
Type Intent Optional Attributes Name
integer(kind=ik), intent(in), dimension(:) :: array
Input array
integer(kind=ik), intent(in) :: n
Number of times to copy input array
Return Value integer(kind=ik), dimension(:,:), allocatable
private pure function tile_1d_real(array, n) result(tiled_array)
Tiles the input array n times. Returns a tiled array that has rank equal to size(shape(array))+1 and that has values equal to values of array, repeated n times. This version is for 1-d input array of reals. This procedure is overloaded by the generic procedure tile.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), dimension(:) :: array
Input array
integer(kind=ik), intent(in) :: n
Number of times to copy input array
Return Value real(kind=rk), dimension(:,:), allocatable
private pure function tile_2d_int(array, n) result(tiled_array)
Tiles the input array n times. Returns a tiled array that has rank equal to size(shape(array))+1 and that has values equal to values of array, repeated n times. This version is for 2-d input array of integers. This procedure is overloaded by the generic procedure tile.
Arguments
Type Intent Optional Attributes Name
integer(kind=ik), intent(in), dimension(:,:) :: array
Input array
integer(kind=ik), intent(in) :: n
Number of times to copy input array
Return Value integer(kind=ik), dimension(:,:,:), allocatable
private pure function tile_2d_real(array, n) result(tiled_array)
Tiles the input array n times. Returns a tiled array that has rank equal to size(shape(array))+1 and that has values equal to values of array, repeated n times. This version is for 2-d input array of reals. This procedure is overloaded by the generic procedure tile.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), dimension(:,:) :: array
Input array
integer(kind=ik), intent(in) :: n
Number of times to copy input array
Return Value real(kind=rk), dimension(:,:,:), allocatable
private pure function tile_3d_int(array, n) result(tiled_array)
Tiles the input array n times. Returns a tiled array that has rank equal to size(shape(array))+1 and that has values equal to values of array, repeated n times. This version is for 3-d input array of integers. This procedure is overloaded by the generic procedure tile.
Arguments
Type Intent Optional Attributes Name
integer(kind=ik), intent(in), dimension(:,:,:) :: array
Input array
integer(kind=ik), intent(in) :: n
Number of times to copy input array
Return Value integer(kind=ik), dimension(:,:,:,:), allocatable
private pure function tile_3d_real(array, n) result(tiled_array)
Tiles the input array n times. Returns a tiled array that has rank equal to size(shape(array))+1 and that has values equal to values of array, repeated n times. This version is for 3-d input array of reals. This procedure is overloaded by the generic procedure tile.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), dimension(:,:,:) :: array
Input array
integer(kind=ik), intent(in) :: n
Number of times to copy input array
Return Value real(kind=rk), dimension(:,:,:,:), allocatable
All Procedures
advect1dRank1 advect1dRank2 advect2dRank2 advectCentered2ndOrder advectCentered2ndOrder1dRank0 advectCentered2ndOrder1dRank1 advectCentered2ndOrder1dRank2 advectCentered2ndOrder2dRank0 advectCentered2ndOrder2dRank1 advectCentered2ndOrder2dRank2 advectUpwind1stOrder advectUpwind1stOrder1dRank0 advectUpwind1stOrder1dRank1 advectUpwind1stOrder1dRank2 advectUpwind1stOrder2dRank0 advectUpwind1stOrder2dRank1 advectUpwind1stOrder2dRank2 assign_array_1d assign_array_2d assign_spectrum_array_1d assign_spectrum_array_2d backward_euler backward_euler_domain backward_euler_spectrum constructor constructor constructor_1d constructor_2d diff diff_1d diff_2d diff_periodic diff_periodic_1d diff_periodic_2d domain_add_domain domain_add_real domain_div_domain domain_div_real domain_mult_domain domain_mult_real domain_sub_domain domain_sub_real domain_type domain_unary_minus donelanHamiltonHui donelanHamiltonHuiDirectionalSpectrum donelanHamiltonHuiDirectionalSpreading elevation eq eq exact_exponential exact_exponential_domain exact_exponential_spectrum forward_euler forward_euler_domain forward_euler_spectrum frequencyMoment frequencyMoment ge getAirDensity getAirDensity getAmplitude getAxisX getAxisY getCurrent_u getCurrent_u getCurrent_v getCurrent_v getDepth getDepth getDepthLevels getDirections getDirections getDirections2d getElevation getElevation getFrequency getFrequency getFrequency2d getGravity getGravity getGrid getGridRotation getGridSpacingX getGridSpacingXWithHalo getGridSpacingY getGridSpacingYWithHalo getGroupSpeed getGroupSpeed getGroupSpeed2d getLatitude getLongitude getLowerBounds getLowerBounds getPhaseSpeed getPhaseSpeed getPhaseSpeed2d getSpectrum getSpectrum getSpectrumArray getSurfaceTension getSurfaceTension getUpperBounds getUpperBounds getWaterDensity getWaterDensity getWaveAction getWavelength getWavenumber getWavenumber2d getWavenumberSpacing gravityClairaut grid_type gt horizontalAcceleration horizontalVelocity integrate integrate_domain integrate_spectrum isAllocated isAllocated isMonochromatic isOmnidirectional jonswap jonswapPeakFrequency le lt meanPeriod meanPeriod meanPeriodZeroCrossing meanPeriodZeroCrossing meanSquareSlope meanSquareSlopeDirectional momentum_x momentum_y momentumFlux_xx momentumFlux_xy momentumFlux_yy neq neq nondimensionalDepth nondimensionalEnergy nondimensionalFetch nondimensionalFrequency nondimensionalRoughness_H1986 nondimensionalRoughness_S1974 nondimensionalTime omnidirectionalSpectrum ones ones_int ones_real peakedness peakFrequency peakFrequencyDiscrete phillips piersonMoskowitz piersonMoskowitzPeakFrequency pressure range range_int range_real readJSON real2d_mult_spectrum real_add_domain real_add_spectrum real_div_domain real_div_spectrum real_mult_domain real_mult_spectrum real_sub_domain real_sub_spectrum saturationSpectrum sbf_DCCM2012 sbf_JONSWAP sds_DCCM2012 sdt_DCCM2012 setAirDensity setAirDensity setCurrent1d setCurrent2d setDepth setDepth setElevation setElevation setGravity setGravity setSpectrum1d setSpectrum1d setSpectrum2d setSpectrum2d setSpectrumArray1d1d setSpectrumArray1d2d setSpectrumArray2d2d setSurfaceTension setSurfaceTension setWaterDensity setWaterDensity significantSurfaceOrbitalVelocity significantWaveHeight significantWaveHeight sin_DCCM2012 snl_DCCM2012 spectrum_add_real spectrum_add_spectrum spectrum_div_real spectrum_div_spectrum spectrum_mult_real spectrum_mult_real2d spectrum_mult_spectrum spectrum_sub_real spectrum_sub_spectrum spectrum_type spectrum_unary_minus stokesDrift stokesDrift2d tile tile_1d_int tile_1d_real tile_2d_int tile_2d_real tile_3d_int tile_3d_real ursellNumber verticalAcceleration verticalVelocity waveAge wavenumber wavenumberMoment wavenumberMoment wavenumberSpectrum writeJSON writeJSON zeros zeros_int zeros_real
Call graph
tile calls tile_2d_int, tile_3d_real, tile_2d_real, tile_1d_int, tile_3d_int, tile_1d_real